name: Deploy frontend
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Download dependencies
        run: npm ci
      - name: Build
        run: npm run build:production
      - name: Deploy to AWS
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" | tr -d '\r' > key.pem
          chmod 400 key.pem
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
          tar -czf cocktailbook-fe.tar.gz -C ./dist/frontend/browser .
          ssh -i key.pem ubuntu@${{ secrets.AWS_HOST }} sudo rm -rf /var/www/cocktailbook/*
          scp -i key.pem cocktailbook-fe.tar.gz ubuntu@${{ secrets.AWS_HOST }}:/home/ubuntu/cocktailbook/cocktailbook-fe.tar.gz
          ssh -i key.pem ubuntu@${{ secrets.AWS_HOST }} sudo tar -xzf /home/ubuntu/cocktailbook/cocktailbook-fe.tar.gz -C /var/www/cocktailbook/
